spring:
  mustache:
    check-template-location: false
  datasource:
    url: jdbc:h2:file:./h2db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    database: postgresql
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
server:
  port: 9090

logging:
  level.org.atmosphere: warn


  # Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,net.zousys.gba
  push:
    enabled: true
    mode: automatic